apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: terraform
spec:
  inputs:
    resources:
    - name: source
      type: git
    - name: workspace
      description: Your terraform workspace
      default: default
  steps:
  - name: init
    image: hashicorp/terraform:light
    workingdir: /workspace/source
    command: ['terraform','init']
    
  - name: plan
    image: hashicorp/terraform:light
    workingdir: /workspace/source
    command: ['terraform','plan', '-out', 'terraform.plan']